os: windows
language: c

script:
  - git clone https://github.com/wy3/luacef.git
  - cd luacef
  - choco feature enable -n=allowGlobalConfirmation
  - choco install mingw --version 5.3.0
  - choco install make
  - choco install curl
  - choco install 7zip
  - curl http://opensource.spotify.com/cefbuilds/cef_binary_3.3112.1659.gfef43e0_windows64_minimal.tar.bz2 --output cef.tar.bz2
  - 7z -y x cef.tar.bz2
  - 7z -y x cef.tar
  - rm cef.tar.bz2
  - rm cef.tar
  - mv cef_binary_3.3112.1659.gfef43e0_windows64_minimal cef_minimal
  - cp ./cef_minimal/Release/libcef.lib ./deps/cef/
  - curl https://www.lua.org/ftp/lua-5.3.5.tar.gz --output lua.tar.gz
  - 7z -y x lua.tar.gz
  - 7z -y x lua.tar
  - mv lua-5.3.5 lua53
  - cd lua53
  - make mingw
  - cd ..
  - cp ./lua53/src/lua.exe ./lua53/
  - cp ./lua53/src/lua53.dll ./lua53/
  - cp ./lua53/src/liblua.a ./deps/lua/liblua53.a
  - rm ./deps/lua/lua53.lib
  - ./lua53/lua.exe build_win.lua
  
