os: windows
language: c

script:
  - choco install mingw --version 5.3.0 -params "/exception:sjlj /threads:win32"
  - choco install lua53
  - git clone https://github.com/wy3/luacef.git
  - cd luacef
