version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command:
            - sudo apt-get update
            - sudo apt-get install gcc
            - sudo apt-get install curl
      - run:
          name: Build
          command:
            - echo Building...
